### ISSUE TITLE
i have a png in a Buffer. i only need to know width + height. fastest way?

### ISSUE THREAD

**Issue by gabor** [lukeapage/pngjs#103]
so i have a png in a Buffer, and i only need to know the width+height. i know i can do this:

```
var pngjs = require('pngjs');
var fs = require('fs');
var buf = fs.readFileSync('img.png');

function getWidthHeight(buf, cb) {
  var png = new pngjs.PNG();
  png.on('metadata', (m) => {
    cb(m.width, m.height);
  });
}
```

the question is, will pngjs still decode the pixels of the image? and if the answer is yes, can i skip that part somehow? i just do not want to waste processing-time on decoding pixels, that i do not need.

**Comment by lukeapage** [comment]
yes it will at present. You could probably import in the specific files to get it to only read the metadata
