### ISSUE TITLE
Node 9.X.X is still broken on v3.3.2

### ISSUE THREAD

**Issue by yanivefraim** [lukeapage/pngjs#105]
https://github.com/lukeapage/pngjs/issues/95 was closed without a proper solution. PNGJS is used on [Puppeteer](https://github.com/GoogleChrome/puppeteer), and build is broken (Node 9) because of that.

**Comment by lukeapage** [comment]
I closed it because a contributor claimed their Pr fixed it.. sorry it didn’t.

I don’t actively maintain pngjs any more.. I’m happy to merge prs and release but I don’t have time to fix this. If you send a Pr I will merge it.
