### ISSUE TITLE
Read then write results in an image bigger than the original

### ISSUE THREAD

**Issue by hipstersmoothie** [lukeapage/pngjs#117]
```js
const fs = require('fs')
const {PNG} = require('pngjs');

const buffer = fs.readFileSync('./exampleImages/dice.png')
const png = PNG.sync.read(buffer)

const outBuffer = PNG.sync.write(png)

console.log(buffer.byteLength, png.data.byteLength, outBuffer.byteLength)
```

OUTPUT:
```
218144 1920000 238523
```

Around 20kb is added to the image regardless of what I do.

**Comment by lukeapage** [comment]
pngjs isn't the most effecient at encoding png's.

The smallest png's are made by trying different filters at max zip levels and working out what gives the best compression - thats quite intensive and not best suited to js.

**Comment by nolimitdev** [comment]
Hi, I have source image 1,8 MB and have also output image bigger (2MB) and deflateLevel does not work at all - any value from 1 to 9 = identical image size. Is it normal? So pngjs is not usable in my case?
