### ISSUE TITLE
parser-sync.js:74 Cannot read property 'interlace' of undefined

### ISSUE THREAD

**Issue by kevzettler** [lukeapage/pngjs#120]
```
index.js:16 TypeError: Cannot read property 'interlace' of undefined
    at module.exports (parser-sync.js:74)
    at Object.exports.read (png-sync.js:10)
```

Throws from: https://github.com/lukeapage/pngjs/blob/ae7b0a1534dbc6d704e4a35458b9181163a51cc2/lib/parser-sync.js#L74

I'm not sure what metadata is supposed to be. Maybe this should guard

`if(metadata && metatdata.interlaced)`

My code is pretty straight forward. Passes an ArrayBuffer to the sync method.
```
import { PNG } from 'pngjs';
import arrayBuffer from './static/peppers.png';
const pepperPng = PNG.sync.read(arrayBuffer);
```

**Comment by sniggyfigbat** [comment]
Hi @kevzettler. I've encountered this same issue. I don't suppose you remember how you resolved it?

Cheers!

**Comment by sniggyfigbat** [comment]
For posterity; You can actually use the async `parse` functionality perfectly effectively for this. Here's a bit of sample code where I use it to read a `fetch` result in-browser (which uses a non-compatible stream interface, very annoyingly):

    let levelStream;
	
	let fetchLevelProm = fetch('./levels/TestLevel.png').then(
		(response) => {
			if (response.status !== 200) {
				console.log('Issue loading level file from server. Status Code: ' + response.status);
				return;
			}
			
			return response;
		}
	)
	.then(response => response.arrayBuffer())
	.then(buffer => {
		levelStream = new PNG({ filterType:4 }).parse( buffer, function(error, data) {
			if (error != null) { console.log('ERROR: In level image read; ' + error); }
			else { GP.loadLevel(levelStream); }
		});
	})
	.catch(function(err) {
		console.log('Fetch Error: ', err);
	});

Don't be confused by it being called 'levelData', I'm just storing data in a perfectly normal PNG.
