### ISSUE TITLE
Does PNGJS work with raw pixel data?

### ISSUE THREAD

**Issue by HRK44** [lukeapage/pngjs#121]
I have a buffer of raw pixel data and want to encode it as a PNG, can I do this using this library?

**Comment by tinico** [comment]
I have the same problem.

**Comment by bjnortier** [comment]
I was looking for the same thing, found this:

https://stackoverflow.com/questions/32259142/how-to-use-pngjs-library-to-create-png-from-rgb-matrix

e.g.

```
var fs = require('fs'),
    PNG = require('pngjs').PNG;

var png = new PNG({
    width: 100,
    height: 100,
    filterType: -1
});

for (var y = 0; y < png.height; y++) {
    for (var x = 0; x < png.width; x++) {
        var idx = (png.width * y + x) << 2;
        png.data[idx  ] = 255;
        png.data[idx+1] = 218;
        png.data[idx+2] = 185;
        png.data[idx+3] = 128;
    }
}

png.pack().pipe(fs.createWriteStream('newOut.png'));
```

**Comment by lukeapage** [comment]
Its already in the examples:
https://github.com/lukeapage/pngjs/blob/master/examples/newfile.js

but the readme doesn't actually point at them, so I'll add a link.
