### ISSUE TITLE
Storing PNG

### ISSUE THREAD

**Issue by Waterbrain** [lukeapage/pngjs#291]
Hello:
I am trying to handle png in memory:
```
var fs = require('fs');
var PNG = require('pngjs').PNG;
const oledsw = ["OledZeroWhite.png", "OledOneWhite.png", "OledTwoWhite.png", "OledThreeWhite.png", "OledFourWhite.png", "OledFiveWhite.png", "OledSixWhite.png", "OledSevenWhite.png", "OledEightWhite.png", "OledNineWhite.png", "OledTwopointsWhite.png", "OledTwopoints.png", "OledCleardigit.png"];
var pngNumbers = [];
var dirresources = __dirname + "/resources/";
oledsw.forEach(function (name) {
               fs.createReadStream(dirresources + name)
				.pipe(new PNG({
					filterType: 4
				}))
				.on('parsed', function () {

					pngNumbers.push(this)
				});
});
```
and I must be doing something wrong, since I can't save the png's in the array.
Somebody could help me?
Thank you

**Comment by Malvineous** [comment]
The code only shows you loading images, with no explanation of what goes wrong or what the array contents look like, so it's impossible to offer any advice.

**Comment by Waterbrain** [comment]
Hello:

Sorry for the delay.

I took over maintenance of the node-red-comtrib-oled repository, and am trying to add a clock node.

This works by doing it from outside the node, and I intend to make it more efficient by keeping the digits in memory.
Now the code is like this:

`try {
					fs.createReadStream(p.image)
					.pipe(new PNG({ filterType: 4 }))
					.on('parsed', function () {					
							self.display.drawRGBAImage(this, p.x || Math.floor((self.display.WIDTH - this.width) / 2), p.y || Math.floor((self.display.HEIGHT - this.height) / 2));
						});
				} catch (err) {
				self.error(err)
				}`

What I want is to have the preloaded digits in an array and be able to use them with drawRGBAImage.

Thanks for your help
