### ISSUE TITLE
Adding multiple Images into a single image 

### ISSUE THREAD

**Issue by RahulVishK** [lukeapage/pngjs#292]
here we have a requirement the we will be having 3 images we need all there images to be collapsed on to single image 
image 1
![download-_1_](https://user-images.githubusercontent.com/97290751/189648367-7e8081e8-3a08-4b62-b106-24f351db9818.png)
image 2
![download](https://user-images.githubusercontent.com/97290751/189648416-ab874f50-07d2-49a9-ba6d-74aaae499666.png)
image 3
![images_1](https://user-images.githubusercontent.com/97290751/189648473-0646f8e9-39cc-4591-8e61-6a44249486b0.png)

FINAL iMAGE
![image](https://user-images.githubusercontent.com/97290751/189649725-407258a3-f863-455e-940d-aacd645e798d.png)

**Comment by Malvineous** [comment]
This is an image manipulation question.  pngjs only handles reading images into arrays and writing them back to .png files again, so this question has nothing to do with pngjs.

You can use pngjs to read the first three images into three arrays, then use your own algorithm to draw those pixels into a fourth array, then save that array to a .png file as your final image.
