### ISSUE TITLE
[Question] How to increase an image height with empty space?

### ISSUE THREAD

**Issue by BrunoQuaresma** [lukeapage/pngjs#296]
Hey folks, I want to compare two screenshots from a website but to make it work, both have to be at the same height. So I'm wondering if there is a way to use pngjs to "complement" the height of the smaller image with an empty space or even a black rectangle. Thanks in advance!

**Comment by Malvineous** [comment]
pngjs is an image read/write library, not an image manipulation library.  You probably want something like ImageMagick.

For pngjs you would have to read the image into an array, then resize your array, then write it back to a file.  But if you have the images as arrays, you might as well just do your screenshot comparison at that point yourself!
