### ISSUE TITLE
How to write a PNG file buffer to be saved given pixel data

### ISSUE THREAD

**Issue by velara3** [lukeapage/pngjs#297]
I have a library that extracts an image into pixel data. Is there example code or documentation that will show how to encode that pixel data into a PNG? Or is there a method that will encode it into a PNG? 

Something like the following: 
```
var data = await myMethod(); // array of RGBA values
var pngFileToSave:ArrayBuffer = PNG.encode(data); // pseudo code
var file = fs.writeFile("mypng.png", pngFileToSave);
```

`Data: `
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1084127/205709127-a3cff711-ada6-4e39-a5d8-72d8b45e36c2.png">

And if there are suggestions to the code above I welcome them. Also, from the examples, I believe I have to add bit depth, color space and size?

**Comment by Abdelaziz18003** [comment]
@velara3 you may want to use https://github.com/scijs/save-pixels, it uses pngjs under the hood. I know this might be a too late response that it no longer relevant for you. However it can be helpful for someone else facing the same problem
