### ISSUE TITLE
permant warning message pngjs2

### ISSUE THREAD

**Issue by iamstarkov** [lukeapage/pngjs#33]
while I’m trying to remove `npm WARN deprecated pngjs2@2.0.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.` from [jimp](https://github.com/oliver-moran/jimp) I found that pnjs2 links to this repo, where name of the package [still `pngjs`](https://github.com/lukeapage/pngjs/blob/master/package.json#L2). so even if I switched to pngjs2 then this warnin still exists.

**Comment by lukeapage** [comment]
as recommended by npm i have taken over pngjs so pngjs2 => pngjs

**Comment by iamstarkov** [comment]
its awkward situation, now even if im using latest pngjs, Im still getting warning. if current repo is okay, can you remove warning message from whole package and deprecate only older versions?

**Comment by lukeapage** [comment]
you shouldn't get a warning using pngjs... please can you post what warning
you get? and/or the package on npm now published with a pngjs dependency
that warns? i can try it out.

**Comment by iamstarkov** [comment]
you will get it easily if you wil try to install jimp
```
npm i jimp
```

**Comment by lukeapage** [comment]
The problem is caused by pixelmatch - that depends on pngsjs2
