### ISSUE TITLE
node-zlib-backport causes browserify builds to fail

### ISSUE THREAD

**Issue by mikolalysenko** [lukeapage/pngjs#50]
Or more generally any browser/bundling module system breaks.  This prevents the use of pngjs in a browser or users from optimizing their deployments using browserify or related transforms.

As a fix, it would be possible to remove the check for node-zlib-backport in parser-sync and packer-sync.

**Comment by lukeapage** [comment]
I believe you can tell browserify to ignore modules (null them out). Thats what another project using browserify with this package is doing.
