### ISSUE TITLE
Save 16 bit per channel

### ISSUE THREAD

**Issue by Xan-Kun** [lukeapage/pngjs#51]
I am a little confused by the table in the readme.
I understand it should be possible to save a PNG with 16 bit per channel, but couldn't find a way (or example) how to do it. The only other library that does not depend on libpng and can handle 16 bit is png-coder, but it doesn't work and can only read 16 bit.
Please excuse the "issue", I am just not sure if it should work and there may be a real issue or if I just understood it wrong.

Thanks a lot!

**Comment by lukeapage** [comment]
I havent looked at this in a while but i think
A) reading - works automatocally
B) writing - send a bitDepth of 16 in the options and then pass data that has 2 bytes per color

Also try looking at the tests,  I may have written 16 bit tests.

Comment back of this doesnt work.

**Comment by Xan-Kun** [comment]
Hello and thanks for answering!
I had a lot of problems with VSCode not showing exceptions and simply stating that "Node.js did not repond to request 'continue' in a reasonable amount of time." and I first thought it had something to do with the project, but it seems to be a VSCode problem...

I experimented a lot and the naive approach does not work

	var newPng = new PNG({
	   filterType: -1,
	   width: 256,
	   height: 256,
	   depthInBytes: 16
	})

	function create(png) {
	   for (var y = 0; y < png.height; y++) {
		  for (var x = 0; x < png.width; x++) {
			 var idx = (png.width * y + x) << (2 + png.depthInBytes - 1);

			 // invert color
			 png.data.writeUInt16BE(0xcafe, idx);
			 png.data.writeUInt16BE(0xcafe, idx + 2);
			 png.data.writeUInt16BE(0xcafe, idx + 4);
			 png.data.writeUInt16BE(0xcafe, idx + 6);
		  }
	   }
	   png.pack().pipe(fs.createWriteStream('out.png'));
	};

	create(newPng)

This leads to a 

	RangeError: Index out of range
		at checkInt (buffer.js:1042:11)
		at Buffer.writeUInt16BE (buffer.js:1109:5)
		at create (D:\CodeSpace\PNGista\index.js:24:19)
		at Object.<anonymous> (D:\CodeSpace\PNGista\index.js:69:1)
		at Module._compile (module.js:541:32)
		at Object.Module._extensions..js (module.js:550:10)
		at Module.load (module.js:456:32)
		at tryModuleLoad (module.js:415:12)
		at Function.Module._load (module.js:407:3)
		at Function.Module.runMain (module.js:575:10)

I was experimenting a lot but didn't really know what to do, so any hint would be very appreatiated :-)

**Comment by lukeapage** [comment]
Why depthInBytes: 16, not bitDepth: 16 ?

**Comment by lukeapage** [comment]
Though seems to be a bug - we dont take it into account when using it this way https://github.com/lukeapage/pngjs/blob/master/lib/png.js#L18

**Comment by lukeapage** [comment]
Ah sorry it seems 16 bit saving isnt supported - ive just seen https://github.com/lukeapage/pngjs/blob/master/lib/packer.js#L23
Not sure why or why the readme is not clear - we definotely read 16 bit ok.

Id love to help fix/implement but im not sure i have enough time. Would accept a pr though.

**Comment by Xan-Kun** [comment]
Thanks for clarifying that, it would explain why I can't get it to work :-)
16bit PNG seems to be a real problem and it seems noone can do it yet.

**Comment by Xan-Kun** [comment]
Maybe the documentation should mention it explicitly.
(And I don't get why it's working with an input file, but not from scratch... *thinking*)

**Comment by lukeapage** [comment]
I dont think support would be hard to add.

**Comment by Xan-Kun** [comment]
I think it will :-)

**Comment by Xan-Kun** [comment]
Ok, I started a new project and first try to understand the behaviour of the filter with 16 bit.
I got stuck when I tested the different channels.
The code is taken from the _16bitTest.js_.

First the code

	var fs = require('fs');
	var PNG = require('png-coder').PNG;

	fs.createReadStream('./my_16bitPerChannel_ps.png')
		.pipe(new PNG({
			filterType: -1
		}))
		.on('parsed', function () {

			var idx = 0;
			var delta = 8;

			for (var y = 0; y < this.height; y++) {
				for (var x = 0; x < this.width; x++) {
					var booY = y * 256
					var booX = x * 256
					var red = 0;
					var green = 0;
					var blue = 0;
					this.data.writeUInt16BE(red, idx);
					this.data.writeUInt16BE(green, idx + 2);
					this.data.writeUInt16BE(blue, idx + 4);
					this.data.writeUInt16BE(0xFFFF, idx + 6);
					idx = idx + delta
				}
			}
			this.pack().pipe(fs.createWriteStream('out.png'));
		});

**Comment by Xan-Kun** [comment]
This code produces a plain black png, as expected:
![out](https://cloud.githubusercontent.com/assets/11686614/15070006/cf972ad8-1381-11e6-84c8-a17e11510407.png)

**Comment by Xan-Kun** [comment]
If I change the red to
                var red = booX;

We get a nice gradient in the x-axis. As expected.
![red_boox](https://cloud.githubusercontent.com/assets/11686614/15070045/281bf1ac-1382-11e6-98cc-eca8196febcf.png)

**Comment by Xan-Kun** [comment]
We can do the same for the y-axis
                var red = booY;

gives us
![red_booy](https://cloud.githubusercontent.com/assets/11686614/15070060/4349f8ca-1382-11e6-9936-ba7dd0bcf706.png)

**Comment by Xan-Kun** [comment]
Now we use the green channel. Let's set red to 0 again and do the same:
                var red = 0;
                var green = booX;

We get

![green_boox](https://cloud.githubusercontent.com/assets/11686614/15070078/5dcf23aa-1382-11e6-84d8-d8b025e7c4af.png)

So far everathing seems fine.

**Comment by Xan-Kun** [comment]
BUT...
                var red = 0;
                var green = booY;

produces

![green_booy](https://cloud.githubusercontent.com/assets/11686614/15070099/7ce4abb6-1382-11e6-8796-5201d5301f4f.png)

That can't be right?!

**Comment by Xan-Kun** [comment]
For future reference:
If the filterType is 0 (i.e.: _filterNone) the result is

![green_booy_0](https://cloud.githubusercontent.com/assets/11686614/15096657/503e922a-1503-11e6-891e-5e62ad0ca3a5.png)

**Comment by jnuevo** [comment]
I have made changes to the code that enable writing 16bit per channel data, and can put a PR if it's of interest.

@lukeapage I have a few questions regarding integration. Please let me know if there's any issue with these:
1. For this feature to be useful, the input data would have to be in 16 bits to being with, so setting `bitDepth = 16` would imply that `data` is 16bits per channel.
2. BigEndian/LittleEndian. I think that requiring the user to pass `data` in BE in LE systems complicates usage too much, and would prefer to pass data in system endianness. So `data` would be created for example:
   
    var w = 10, h = 20;
    var buffer = new Buffer(2 * w * h);
    var bitmap = new Uint16Array(buffer.buffer);
    for (var i = 0; i < h; i++) {
       for (var j = 0; j < w; j++) bitmap[i * w + j] = i * 65535 / h;
    }
    png.data = buffer;

and then internally we change the data to BE.

Thanks.

**Comment by Xan-Kun** [comment]
Hi there! Quite a while and I am not sure how I solved it in the end :-)
Thanks for the change and I will keep in mind, that pngjs seems to be the only one getting that right now.
