### ISSUE TITLE
Make a version for a browser

### ISSUE THREAD

**Issue by photopea** [lukeapage/pngjs#53]
Hi, we would like to use your library in www.photopea.com . Can you make your code independent on Node.js environment?

**Comment by lukeapage** [comment]
Hi,

I am running short on time at the moment, so I don't have time for this. I'd accept a PR to do this, but also it is possible today using browserify - it can replace references to zlib with a wrapped browser version of pako. See https://github.com/devongovett/browserify-zlib

You also need to tell browserify to ignore the zlib-backport library that is optionally included.

**Comment by gforge** [comment]
I've created a forked package with the creative name `pngjs3` that you can find here: https://github.com/gforge/pngjs3 with browser support

**Comment by photopea** [comment]
It is OK, I already made https://github.com/photopea/UPNG.js , which is probably the best JS library for PNGs today :) (includes lossless and lossy PNG encoding). I built  https://upng.Photopea.com with it.

**Comment by gforge** [comment]
Awesome, looks like a great package. One big main file is though a little hard to grasp, adding ES6 with transpiling is a nice feature.

**Comment by amynbe** [comment]
Resolved by #98 -- can someone please merge that
