### ISSUE TITLE
Support for DPI change

### ISSUE THREAD

**Issue by asturur** [lukeapage/pngjs#70]
I'm interested in DPI change for png file format.
I would be available to build it.

Is a feature you are interested in?

**Comment by lukeapage** [comment]
I think that would be better in its own package. Sorry and thanks.

**Comment by patheticcockroach** [comment]
@asturur Did you end up making a separate package for this? (or did you find manybe another package that can do it?

**Comment by asturur** [comment]
I did! is not on NPM yet.
Can change DPI of PNG or JPEG on dataurls or blob, and is very fast.

Please add me to twitter `AndreaBogazzi` is my handle, as soon as is out i will shout about it.

**Comment by votiakovbogdan** [comment]
@asturur when you will release it?Can you say how did you do this?

**Comment by asturur** [comment]
Since i did at work, i m waiting for people to give me the ok. I hope soon.
Please add me on twitter, i ll for sure tweet it.

**Comment by asturur** [comment]
@patheticcockroach i know lot of time passed, but the lib is on npm now and is called changedpi
find it also here:
github.com/shutterstock/changedpi

**Comment by ycmjason** [comment]
@asturur you made my day.

**Comment by asturur** [comment]
cool! Tweet about it if you have an account and ping @shutterstock or @shuttertech since it was their idea to make it possible an open release
