### ISSUE TITLE
pngjs alternative

### ISSUE THREAD

**Issue by photopea** [lukeapage/pngjs#77]
Hi guys,
I was looking for a good PNG parser for years, but all I could find required Node.js environment (I have no experience with Node.js, I run everything on the client side).

I wrote my own library UPNG.js https://github.com/photopea/UPNG.js and I am confident to say, that it fully supports the PNG specification (all combinations of interlacing, color types and channel depths). You can open your PNGs at www.Photopea.com to see, if UPNG.js parses them correctly.

It can be useful when you want to parse PNGs on the client side without Node.js. Or it can be an inspiration for fixing possible bugs in this library. Let me know what you think :)

**Comment by lukeapage** [comment]
Thanks for the plug to your library. I am no longer actively maintaining this, just merging any contributions.

**Comment by photopea** [comment]
Oh, I see. So maybe you could put a link to UPNG.js in the front page of this repository, so people can use up-to-date library? UPNG.js has an encoder function now, which can do quantization (minification).
