### ISSUE TITLE
Compression text using png 8

### ISSUE THREAD

**Issue by jimmywarting** [lukeapage/pngjs#83]
Hi, i'm trying to achieve the same thing this guy did:
 
https://web.archive.org/web/20120212153739/http://blog.nihilogic.dk/2008/05/compression-using-canvas-and-png.html

I'm wondering if someone would like to help me convert this to javascript.
I don't know how to make a 8 bit image or even know what monochromatic noise compresses means

**Comment by lukeapage** [comment]
Closing as this is a question and quite old.
