### ISSUE TITLE
Reading 16-bit per channel retrieves 8-bit data

### ISSUE THREAD

**Issue by binary-animal** [lukeapage/pngjs#87]
Exact meaning of "Support for reading 1,2,4 & 16 bit files" in documentation is not clear.

If it means "it can read 16 bit files and provide access to 16 bit color data inside png object" then something strange happens because after successful read of 16-bit png data array contains only upper 8 bits of real color data, so it drops somehow a half of color information.

If it means just "it can read 16-bit files without errors and represent them as 8-bit per color png" then the question is: do you plan to make full read support of 16-bit per channel png?

created 16-bit color data (viewed as Uint8Array):
![created 16-bit color data](https://user-images.githubusercontent.com/1168664/29253331-280f2f30-8082-11e7-992f-b8f9121aba11.png)

png object after reading of created and successfully saved 16-bit png
![png object after reading created and successfully saved to file 16-bit png](https://user-images.githubusercontent.com/1168664/29253343-883817aa-8082-11e7-88ac-f3125338d682.png)

**Comment by binary-animal** [comment]
I've found that formatNormaliser function is always applied while parsing. And it always drops half of color information in case of 16-bit input.
What about making this behavior a little less straightforward by adding some option for disabling/enabling normalization?

**Comment by gforge** [comment]
I've added an option to skip the rescaling that you can find here: https://github.com/gforge/pngjs/tree/optional_rescaling

**Comment by gforge** [comment]
@binary-animal created a new package `pngjs3` that with this bug fixed, ES6 updates and more: https://github.com/gforge/pngjs3
