### ISSUE TITLE
Version 3.3.0 introduced es6 syntax

### ISSUE THREAD

**Issue by radsaq** [lukeapage/pngjs#88]
Version 3.3.0 uses es6 syntax at https://github.com/lukeapage/pngjs/pull/82/files#diff-1b0965e27e225f29dcb37b15b20a7ac0R83 which means pngjs will no longer work in older browser. Seems like this should either be fixed or documented.

**Comment by jnuevo** [comment]
Is it just that line? Please make a PR with the change

**Comment by lukeapage** [comment]
is it Int16Array/UInt16Array ? I can't see anything specific.
Am happy to receive a PR to document or to fix the code or you can pin to 3.2

**Comment by jnuevo** [comment]
I think it is Line 88, how the returned object is created. Fixed on PR #94.

**Comment by radsaq** [comment]
Yeah, sorry, it is the shorthand syntax in the return value so #94 will fix it.

**Comment by gforge** [comment]
I've created an ES6 version that uses babel, I've restructured the classes and moved some file groups into subfolders as I found the code a little hard to navigate, you can find it here: https://github.com/gforge/pngjs/tree/es6

@lukeapage do you think its worth merging into your lib?

**Comment by lukeapage** [comment]
@gforge sorry I missed your message.. I don't usually have time to do any maintenance here. I'll raise a PR
