### ISSUE TITLE
Only first line in output changed correctly after sync data buffer manipulation

### ISSUE THREAD

**Issue by PMK89** [lukeapage/pngjs#89]
My function should read a png file, changes white or black to transparent and writes it back to a file.
The change inside the buffer seems correct (used a text log on a small file and all pixels are changed correctly) but in the output only the first line is transparent, sometimes a few others are yellow but most lines don't change at all. I already tried different filter and colorType options.

The code is quite similar to the example and is shown bellow:

```
const filepath = './dist/assets/images/' + arg.file;
var pngbuffer = fs.readFileSync(filepath);
var png = PNG.sync.read(pngbuffer);
var num = 255;
if (arg.color === 'black') {
  num = 0;
}
const nx = png.width;
const ny = png.height;
for (var y = 0; y < ny; y++) {
  for (var x = 0; x < nx; x++) {
    var idx = (nx * y + x);
    if (png.data[idx] === num && png.data[idx+1] === num && png.data[idx+2] === num) {
      png.data[idx+3] = 0;
    }
  }
}
var newpngbuffer = PNG.sync.write(png);
var newfilename = arg.file.replace('pmk', '_pmk');
const newfilepath = './dist/assets/images/' + newfilename;
fs.writeFileSync(newfilepath, newpngbuffer);
```

**Comment by lukeapage** [comment]
The `idx` init is wrong, it doesn't power to the bpp.
