### ISSUE TITLE
TypeError: pxData.copy is not a function

### ISSUE THREAD

**Issue by joliejuke-orga** [lukeapage/pngjs#92]
I have this error `TypeError: pxData.copy is not a function`
When I use the function:
```
let pixelData = [...];
let png = new Png({
        width: 50,
        height: 50
});
png.data = pixelData;
let buffer = PNG.sync.write(png, {colorType: 6});
```

**Comment by lukeapage** [comment]
I'm happy to receive a PR if you can track down the problem

**Comment by gamegee** [comment]
Hi, I'm really not sure how the problem should be fixed, but it seems that you're trying to call copy function on the pixelData which is an array.

```
function filterNone(pxData, pxPos, byteWidth, rawData, rawPos) {
  return pxData.copy(rawData, rawPos, pxPos, pxPos + byteWidth);
}
```

Maybe we should just return the pxData?
```
function filterNone(pxData, pxPos, byteWidth, rawData, rawPos) {
  return pxData;
}
```
Or does the copy function has a more important role than just copy.
