### ISSUE TITLE
Any idea why pngjs would be extremely slow when running in a Jest test?

### ISSUE THREAD

**Issue by mattblang** [lukeapage/pngjs#96]
I've created [an issue](https://github.com/facebook/jest/issues/4972#issuecomment-349340452) on the [Jest](https://github.com/facebook/jest) repository but unfortunately it was closed. I'm running the exact same code both in a Jest test and a Node script. In the Jest test it takes **thirty** seconds to run while in the Node script only **four** seconds. I've pinpointed the issue to a line that uses `pngjs` and `fs` to write a PNG to the file system. I went on to do a [CPU profile](https://user-images.githubusercontent.com/1845257/33592411-7b03cd78-d950-11e7-91f3-3756dab16374.png) that seems to indicate `pngjs` as the culprit. But again, the strange thing here is that the slowdown only happens when being run inside of the Jest test.

**Comment by mattblang** [comment]
Just wanted to reference [this issue](https://github.com/americanexpress/jest-image-snapshot/issues/28) that I made on the `jest-image-snapshot` matcher repository, as well as [this issue](https://github.com/mattblang/jest-image-comparison-perf-repro/issues/1) that the maintainer of `jest-image-snapshot` and I have worked on to provide a barebones example that reproduces the issue. There is definitely something really weird happening when `pngjs` is writing a file to disk within a `Jest` test.

**Comment by robertmain** [comment]
Can you link me to your usage? I'm having problems with the contents of `this.data` seeming not to be a PNG...

**Comment by mattblang** [comment]
Turns out this is due to Math calls running several orders of magnitude slower in Jest. [Here](https://github.com/facebook/jest/issues/5163) is a ticket opened on the Jest repo.
